apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tap-gui-catalog-info
  description: A sample catalog for Backstage
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./components/blockchain-api.yaml
    - ./groups/tanzu-se-southeast-team.yaml
    - ./systems/blockchain.yaml
    - ./domain/blockchain-domain.yaml
