apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: blockchain-api
  namespace: blockchain-apis
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=blockchain-api"
spec:
  type: service
  lifecycle: experimental
  owner: tanzu-se-southeast-team
  providesApis:
    - blockchain-api/blockchain-api-dev
